# Generated by Django 5.0.7 on 2026-06-14 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_events', '0001_initial'),
        ('departments', '0002_alter_department_hod'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='departments.department'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='type',
            field=models.CharField(choices=[('exam', 'Exam'), ('holiday', 'Holiday'), ('event', 'Event'), ('deadline', 'Deadline'), ('academic', 'Academic')], default='event', max_length=20),
        ),
    ]
