# Generated by Django 6.0.6 on 2026-06-12 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
        ('courses', '0001_initial'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='scope',
            field=models.CharField(choices=[('system', 'system'), ('department', 'department'), ('course', 'course')], default='system', max_length=15),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='courses.course'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='departments.department'),
        ),
    ]
