# Generated by Django 5.0.7 on 2026-06-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
