# Generated by Django 5.0.7 on 2026-06-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_reset_code_user_reset_code_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agreed_to_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='fees_paid',
            field=models.BooleanField(default=False),
        ),
    ]
