# Generated by Django 6.0.6 on 2026-06-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='academic_year',
            field=models.CharField(default='2026-27', max_length=20),
        ),
    ]
