# Generated by Django 6.0.6 on 2026-06-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officehour',
            name='bookings',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
