# Generated by Django 6.0.6 on 2026-06-13 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_alter_department_hod'),
        ('feedback', '0002_officehour_bookings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='message',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='subject',
        ),
        migrations.AddField(
            model_name='feedback',
            name='category',
            field=models.CharField(default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='feedback',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='departments.department'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='target_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='target_type',
            field=models.CharField(default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='officehour',
            name='max_slots',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL),
        ),
    ]
