# Generated by Django 6.0.6 on 2026-06-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendanceeditrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
