# Generated by Django 6.0.6 on 2026-06-12 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=20)),
                ('academic_year', models.CharField(default='2026-27', max_length=50)),
                ('schedule', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='departments.department')),
            ],
            options={
                'db_table': 'timetables',
                'ordering': ['-created_at'],
            },
        ),
    ]
