# Generated by Django 6.0.6 on 2026-06-13 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_result_is_published_result_remarks'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='subjects.subject'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='type',
            field=models.CharField(choices=[('Theory', 'Theory'), ('Practical', 'Practical'), ('Viva', 'Viva'), ('mid', 'mid'), ('final', 'final'), ('quiz', 'quiz'), ('assignment', 'assignment'), ('practical', 'practical')], default='Theory', max_length=20),
        ),
    ]
