# Generated by Django 5.0.7 on 2026-07-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_exam_academic_year_exam_subject_alter_exam_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='type',
            field=models.CharField(choices=[('Theory', 'Theory'), ('Practical', 'Practical'), ('Viva', 'Viva'), ('mid', 'mid'), ('final', 'final'), ('quiz', 'quiz'), ('weekly', 'weekly'), ('Weekly Test', 'Weekly Test'), ('assignment', 'assignment'), ('practical', 'practical'), ('unit_test_1', 'Unit Test 1'), ('unit_test_2', 'Unit Test 2'), ('Unit Test 1', 'Unit Test 1'), ('Unit Test 2', 'Unit Test 2')], default='Theory', max_length=20),
        ),
    ]
