# Generated by Django 6.0.6 on 2026-06-13 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_materials', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.subject'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='type',
            field=models.CharField(choices=[('Notes', 'Notes'), ('Assignments', 'Assignments'), ('Past Papers', 'Past Papers'), ('References', 'References'), ('Lab Manuals', 'Lab Manuals'), ('pdf', 'pdf'), ('note', 'note'), ('ppt', 'ppt'), ('video', 'video'), ('question_paper', 'question_paper')], default='Notes', max_length=30),
        ),
    ]
